name: "publish"
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install frontend dependencies
        run: npm install
      - name: Write Tauri Key to File
        env:
          TAURI_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        run: |
          echo "$TAURI_KEY" > tauri-key.key
      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY_PATH: ${{ github.workspace }}/tauri-key.key
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SITE_URL: https://xinhgroup.vercel.app
          IS_TAURI: 'true'
        with:
          tagName: v__VERSION__
          releaseName: "ERP-App v__VERSION__"
          releaseBody: "Bản build chính thức. Vui lòng tải file .exe bên dưới. Bản cập nhật sẽ được thông báo tự động."
          releaseDraft: true
          prerelease: false

      - name: Generate Manifest and Sign
        env:
          TAURI_SIGNING_PRIVATE_KEY_PATH: ${{ github.workspace }}/tauri-key.key
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        run: node scripts/generate-manifest.js
        
      - name: Get exact version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
        shell: bash

      - name: Upload Missing Signature and Manifest
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          draft: true
          files: |
            src-tauri/target/release/bundle/nsis/*.sig
            src-tauri/target/release/bundle/nsis/latest.json
